### PR TITLE
Add CPP for backwards compatible http-client + http-conduit

### PR DESCRIPTION
**Pull request by nhibberd**
! @charleso @jystic @erikd-ambiata 

Based on https://github.com/brendanhay/amazonka/commit/0656b5a12001a1d32cca65cf69f6327d3fcef858
/jury approved @erikd-ambiata

### CODE REVIEW

**Comment by nhibberd** [comment]
Testing with
- [ ] http-client 0.4.18.1
- [ ] http-client 0.4.31.1
- [ ] http-client 0.5.7.1

**Comment by erikd-ambiata** [comment]
Seems reasonably sane. How are you forcing different versions? With the lock file?

**Comment by nhibberd** [comment]
Yeah that’s what I was doing locally

**Comment by erikd-ambiata** [comment]
👍 when it builds and passes tests!

**Pull request merged**
