### PR TITLE
Maybe Owner

### PR DESCRIPTION
**Pull request by nhibberd**
ambiata/mismi#117

### CODE REVIEW

**Comment by etorreborre** [comment]
:100: There are no tests in Amazonka I suppose. Is it hard to add a corresponding test in mismi?

**Comment by nhibberd** [comment]
Long story short. `paginate` and the generated `AWSPager` instances only support the use of delimiter. The specs tell that `NextMarker` is only returned when you specify a delimiter in the request, hence the hacks

**Comment by charleso** [comment]
@nhibberd You want to bump the version and the API doc? Also need to raise (separate) issues against `amazonka` as well.

**Comment by nhibberd** [comment]
Yeah i will when i can confirm these changes are 100%. Do people have thoughts on the `AWSPager` code?

**Comment by charleso** [comment]
That paging stuff is very scary:

http://docs.aws.amazon.com/AmazonS3/latest/dev/ListingObjectKeysUsingJava.html

**Pull request merged**
